### ISSUE TITLE
Bug when copying arrays of objects which contain references to the same function 

### ISSUE THREAD

**Issue by jdthorpe** [sasaplus1/deepcopy.js#10]
dc = require('deepcopy')
	function foo(x,y){return x + y}
	a = {x:foo,y:'asdf'}
	b = {s:foo,t:'asdf'}
	dc([a,b])
	#> [ { x: [Function: foo], y: 'asdf' },
	#>   { s: [Function: foo], t: [Function: foo] } ]

**Comment by sasaplus1** [comment]
@jdthorpe Thank you for your bug report! I fixed it.
