### ISSUE TITLE
Issue When Source contains an Empty array and Function

### ISSUE THREAD

**Issue by saumitrabhave** [sasaplus1/deepcopy.js#11]
https://tonicdev.com/575e8e11175fc41200670e0d/575e8e11175fc41200670e0e

**Comment by saumitrabhave** [comment]
`var copy = require("deepcopy");

var src = {'name':'Name1','title':'Title1','variationType':'VAR1','message':(function (ctx, cb) { return console.log("ABCD"); }),'id':'ID1','tokens':[]};

var target = copy(src);

console.log(target);`

In Case Link gets invalidated.

**Comment by sasaplus1** [comment]
I fixed it. Thanks!

**Comment by saumitrabhave** [comment]
Thanks, Any Idea why this issue is not reproducible on Mac and happens only on *NIX?
