### ISSUE TITLE
[BUG] Invalid recursive copy result in the latest version 0.6.2

### ISSUE THREAD

**Issue by faressoft** [sasaplus1/deepcopy.js#12]
Comparison between 0.6.2 and 0.6.1.

<img alt="screen shot 2016-06-13 at 2 17 41 pm" src="https://cloud.githubusercontent.com/assets/1908658/16005759/9f9af7fc-3171-11e6-87e4-f59172d2f356.png">

This bug is available in the latest version of the deepcopy (0.6.2), the version (0.6.1) if fine.

Code
```js
var services = {
  'name': 'datatable_users',
  'path': '/datatable/users',
  'method': 'get',
  'params': {
    'aaa': {
      'required': false
    }
  }
};

console.log(deepcopy(services));
```

Output
```js
{
  name: 'datatable_users',
  path: '/datatable/users',
  method: 'get',
  params: 'get'
}
```

The `params` gets the value of the previous key.

**Comment by sasaplus1** [comment]
I fixed it. Thanks!
