### ISSUE TITLE
deepcopy doesn't copy Maps

### ISSUE THREAD

**Issue by nschoe** [sasaplus1/deepcopy.js#14]
Hi,

it seems that deepcopy discard `Map` elements.
Here is a snippet of code from an interactive node session:

``` Javascript
> const deepcopy = require ('deepcopy')
undefined
> let m = new Map()
undefined
> m.set ('key', 'value')
Map { 'key' => 'value' }
> let original = {foo: 'bar', theMap: m}
undefined
> original
{ foo: 'bar', theMap: Map { 'key' => 'value' } }
> let copy = deepcopy (original)
undefined
> copy
{ foo: 'bar', theMap: {} }
```

Is there any plans to support Map in the near future?
Cheers.

**Comment by sasaplus1** [comment]
Hi, @nschoe.

I have plans for support for Map, but I've been busy these days.

If you are hurry, you can use the `customizer` of second argument. ex:

```js
var deepcopy = require('deepcopy');

var m = new Map();

m.set('key', 'value');

var original = {
  foo: 'bar',
  theMap: m
};

function cloneMap(target) {
  var clone;

  if (Object.prototype.toString.call(target) === '[object Map]') {
    clone = new Map();

    target.forEach(function(value, key) {
      clone.set(key, deepcopy(value, cloneMap));
    });

    return clone;
  }
}

var copy = deepcopy(original, cloneMap);
```

**Comment by Shinepans** [comment]
But how to clone a Map?
for example:

```
var m = new Map();
m.set('key', {something: 'a', others: 'b'})
var source = m.get('key');
var copy = deepcopy(source);
```

above will throw an Error like this:

> TypeError: Cannot set property length of #<Store> which has only a getter
    at recursiveCopy (..\node_modules\deepcopy\lib\index.js:85:16)
    at recursiveCopy (..\node_modules\deepcopy\lib\index.js:85:25)
    at recursiveCopy (..\node_modules\deepcopy\lib\index.js:85:25)
   ...
    at deepcopy (..\node_modules\deepcopy\lib\index.js:35:10)

### can you help me?

**Comment by sasaplus1** [comment]
I tried your written example code, but doesn't throw error:

```js
var deepcopy = require('deepcopy');

var m = new Map();
m.set('key', {something: 'a', others: 'b'})
var source = m.get('key');
var copy = deepcopy(source);

console.log(copy); // => { something: 'a', others: 'b' }
```

**Comment by Shinepans** [comment]
Hi, : ), Thank you !
The codes above is not my real codes, It's my example,
the error happened when I copy a Map,
And in Map, some value is mongodb docs which are found by querys.
like:
```javascript
var m = new Map();
DataDB.find({some: 'test'), function (err, result) { m.set('mongod', result)});
var source = m.get('mongod');
var copy = deepcopy(source);
```

and then, it throw the errors above. I don't know why, I will try to find it out.

Thank you! I like the **deepcopy**

**Comment by sasaplus1** [comment]
@Shinepans Thanks to use deepcopy.js 😃 

deepcopy.js does not support MongoDB.
It error is not the problem of Map maybe.
But I not know MongoDB. Issue #6 may help to you.

**Comment by sasaplus1** [comment]
support Map on ver.1.0.0
