### ISSUE TITLE
CSP (Content Security Policy) problem.

### ISSUE THREAD

**Issue by OperKH** [sasaplus1/deepcopy.js#21]
I use this libruary in project and currently we implementing CSP.
And browser shows error: `Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive...` it is because of  in `copy_map.js` you using the code: `const globalObject = Function('return this')();` - that makes 'unsafe-eval'

**Comment by sasaplus1** [comment]
@OperKH I tried fix to CSP problem via ver.1.0.1. Can you test it?

**Comment by OperKH** [comment]
@sasaplus1 awesome! Works great now!
