### ISSUE TITLE
Support for MongoDB ObjectId

### ISSUE THREAD

**Issue by umaxfun** [sasaplus1/deepcopy.js#6]
Hi there!

Thanks for your library. I've encountered a problem with deepcopy: it cannot correctly clone ObjectId fields. 

I've written a polyfill that correctly transforms it to string (added to _copyValue, deepcopy.js:147): 
```javascript
    if (typeof value === "object" && value != null && value.hasOwnProperty("_bsontype")) {
      return value.toHexString();
    }
```

**Comment by sean-hill** [comment]
I just encountered this same issue :+1:

**Comment by sasaplus1** [comment]
version 0.6.0 support customizer function. please use this.

```js
deepcopy(target, function(target) {
  if (target.hasOwnProperty('_bsontype')) {
    return target.toHexString();
  }
});
```
